version: '3.3'
services:
    run:
        build:
          context: .
          dockerfile: Dockerfile.dev
        container_name: svelte_template
        ports:
            - '3000:3000'
        volumes:
            - ./src:/usr/src/app/src:z
        